version: 2
updates:
  - package-ecosystem: cargo
    directory: /tauri-plugin-background-service
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: tauri-plugin-background-service/guest-js
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
